/* SPDX-License-Identifier: MIT */
/* GENERATED by scripts/export-board-theme.ts in the endgames repo. Do not edit. */
#pragma once
#include "lvgl.h"

/* v2 tokens (dark). Opaque hex colors only; rgba tokens are not exported. */
#define EG_BG_VOID lv_color_hex(0x08001F)
#define EG_BG_NIGHT lv_color_hex(0x150045)
#define EG_BG_HAZE lv_color_hex(0x2A1166)
#define EG_BG_MIST lv_color_hex(0x3F1F8C)
#define EG_BG_STAGE lv_color_hex(0x150045)
#define EG_SURFACE lv_color_hex(0x2A1166)
#define EG_CYAN lv_color_hex(0x00F0FF)
#define EG_CYAN_DEEP lv_color_hex(0x008BA8)
#define EG_PINK lv_color_hex(0xFF2EB1)
#define EG_PINK_SOFT lv_color_hex(0xFF71CE)
#define EG_MAGENTA lv_color_hex(0xFF006E)
#define EG_PURPLE lv_color_hex(0xB967FF)
#define EG_MINT lv_color_hex(0x00FFA1)
#define EG_YELLOW lv_color_hex(0xFFF200)
#define EG_ORANGE lv_color_hex(0xFF9F1C)
#define EG_PEACH lv_color_hex(0xFFB3BA)
#define EG_LAVENDER lv_color_hex(0xE0E0FF)
#define EG_WHITE lv_color_hex(0xFFFFFF)
#define EG_FG lv_color_hex(0xFBFAFF)
#define EG_FG_HAZE lv_color_hex(0xC9B8FF)
#define EG_FG_MIST lv_color_hex(0xA691EA)
#define EG_FG_ON_LIGHT lv_color_hex(0x2A1166)

/* Board palettes. Default: sunset. */
#define EG_BOARD_SUNSET_LIGHT lv_color_hex(0xFFD1A4)
#define EG_BOARD_SUNSET_DARK lv_color_hex(0x2E1A5C)
#define EG_BOARD_SUNSET_EDGE lv_color_hex(0x00F0FF)
#define EG_BOARD_SUNSET_SHADOW lv_color_hex(0xFF2EB1)
#define EG_BOARD_HOTPINK_LIGHT lv_color_hex(0xFFD1FE)
#define EG_BOARD_HOTPINK_DARK lv_color_hex(0x4A0F4A)
#define EG_BOARD_HOTPINK_EDGE lv_color_hex(0xFFF200)
#define EG_BOARD_HOTPINK_SHADOW lv_color_hex(0x00F0FF)
#define EG_BOARD_CYBER_LIGHT lv_color_hex(0xB8F0FF)
#define EG_BOARD_CYBER_DARK lv_color_hex(0x001433)
#define EG_BOARD_CYBER_EDGE lv_color_hex(0xFF2EB1)
#define EG_BOARD_CYBER_SHADOW lv_color_hex(0x00FFA1)
#define EG_BOARD_MINTLY_LIGHT lv_color_hex(0xC9FFE5)
#define EG_BOARD_MINTLY_DARK lv_color_hex(0x001A12)
#define EG_BOARD_MINTLY_EDGE lv_color_hex(0xFF71CE)
#define EG_BOARD_MINTLY_SHADOW lv_color_hex(0xFFF200)
#define EG_BOARD_MALL_LIGHT lv_color_hex(0xFFE5E5)
#define EG_BOARD_MALL_DARK lv_color_hex(0x9C4A82)
#define EG_BOARD_MALL_EDGE lv_color_hex(0x00FFA1)
#define EG_BOARD_MALL_SHADOW lv_color_hex(0x00F0FF)

#define EG_BOARD_LIGHT EG_BOARD_SUNSET_LIGHT
#define EG_BOARD_DARK EG_BOARD_SUNSET_DARK
#define EG_BOARD_EDGE EG_BOARD_SUNSET_EDGE
#define EG_BOARD_SHADOW EG_BOARD_SUNSET_SHADOW

/* Last-move highlight, same as the website: pink tint (alpha 0-255), yellow ring on the destination. */
#define EG_LASTMOVE_ALPHA_LIGHT 82   /* --lastmove-light 0.32 */
#define EG_LASTMOVE_ALPHA_DARK 128   /* --lastmove-dark 0.50 */
#define EG_LASTMOVE_RING EG_YELLOW
